# Exported from Render on 2024-03-28T14:42:38Z
services:
- type: web
  name: cantina
  runtime: python
  repo: https://github.com/Andrade-Nil/cantina_py
  branch: main
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python3 app.py
version: "1"